name: FC_AEMCraft
main: me.Destro168.FC_AEMCraft.FC_AEMCraft
version: 1.51
description: Custom Plugin for FC_AEMCraft.
commands:
   aem:
      description: Handles aemcraft commands.
depend: [FC_Suite_Shared]